### ISSUE TITLE
Custom sleeves appear as a white box... but only to one particular person

### ISSUE THREAD

**Issue by Butterwings** [Silverfeelin/Starbound-OutfitGenerator#15]
So, I see my character fine. I used the sleeve generator to give my avian character wings:
https://i.gyazo.com/86fe9a3f951204d5724f76a011b4e9cb.png
Most people do.
Except this one person, who sent me this screenshot:
https://cdn.discordapp.com/attachments/402247830519152642/546203026059296801/unknown.png
They similarly see anyone else using custom sleeves as white boxes as well.
They're running Windows 10, 64 bits. What could be happening here?

**Comment by Silverfeelin** [comment]
They might be running a mod that changes their existing assets. If it's only the sleeves and only that person they most likely have a modified `aviantier6schest` chest.

The way these custom drawables work is that it takes an existing item and recolors the textures using directives. For example, `?replace;ffffff=000000` turns any white pixels black. The outfit generator takes this one step further by cropping and stretching the source image so that each pixel of each frame of both sleeves can be replaced individually. The method relies specifically on the base item because of the algorithm Nettle Boy came up with, so any changes to the base item would lead to undesired results.

**Comment by Butterwings** [comment]
Having found and installed a mod that modifies the toucan breastplate's sprite, it did cause all custom sleeves to render as *black* boxes. Similar enough that this is probably the cause, but it can't be the exact same mod they have or it would have been a white box. I'm going to attempt overriding these sprites to their vanilla version using a mod with a higher priority (which is installed on the server we both play on) and see if that fixes it for him without needing to dig through the insane amount of mods he has installed to find the culprit.

**Comment by Butterwings** [comment]
This worked. Thanks
